version:  '3.7'
services:
  db:
    image: postgres:11
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/data/:/var/lib/postgresql/data:z
    environment:
      POSTGRES_PASSWORD: root
  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    ports:
      - 8001:8080
  nginx:
    container_name: nginx
    build: docker/nginx
    ports:
      - 8000:80
    volumes:
      - ../Foody:/var/www/foody
  foody:
    container_name: foody
    build: docker/php-fpm
    working_dir: /var/www/foody
    volumes:
      - ../Foody:/var/www/foody
